### ISSUE TITLE
Kanboard | Request Dockerfile

### ISSUE THREAD

**Issue by Tabaluga** [bestlibre/hassio-addons#1]
Dear @bestlibre,

since two months I'm learning Docker onto the Raspberry Pi and your repositories and Dockerfiles are a great help and inspiration to me to understand how the eco-system of Docker works.

Currently I'm trying to get [Kanboard](https://kanboard.net/) running onto the Rasperry Pi but im stuck even after reading the official setup guide and studying the official Dockerfiles.

I recognized that you're the only person who has created an Kanboard image for  the Rasperry Pi [bestlibre/armhf-kanboard](https://hub.docker.com/r/bestlibre/armhf-kanboard/) which works great out of the box where I failed.

I want to ask if you could share your building files (Dockerfile and additional files) so I can learn how you've succeded this.

Please excuse that I'm opening an Issue here, but I've found no other contact information to reach out to you.

Best regards

**Comment by bestlibre** [comment]
I have put them [here](https://github.com/bestlibre/hassio-addons/tree/master/kanboard). This is a standalone container. It launch both php and nginx. It is not ideal since both services are inside one container, but if you do not need another nginx or php on another container, it is ok. I had to do that because in the hass.io addons ecosystem it is not (yet) possible to link containers volumes with others.

If you are in a standard docker environment, the way to go would be to have three containers : 
-  One for nginx,
-  One for php,
-  One for kanboard
You would them use docker compose or command line switch to share data between those containers.

cf for example this site for a more detailed [how-to](http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/)
