### ISSUE TITLE
Mopidy shows older version

### ISSUE THREAD

**Issue by cogneato** [bestlibre/hassio-addons#46]
Mopidy version installed today (0.1.2) is older than one which another user has installed from days ago (0.2.2). 0.1.2 will not start, and options will not save.

**Comment by bestlibre** [comment]
Sorry for the delay. Is it still an issue ?

**Comment by ndarilek** [comment]
Yes, still an issue. Not sure what the fix is. Happens on a fresh HassOS install, RPi 3, 32-bit. Literally the first thing I did after the install came up was add this repo and check the Mopidy version. I had this issue on a previous install, and I thought a fresh installation would resolve it.

Thanks!

**Comment by robferrero** [comment]
Yes, still an issue, I have the same problem on a HassIO install on a RPi with only SSH and Hass Configurator enable
